theme: jekyll-theme-slate
title: Aaron Eberhart
description: | [Publications](papers.md) | [Projects](projects.md) |  [Data Semantics Lab](https://daselab.cs.ksu.edu/) | [CV](cv.md) |
show_downloads: false
